#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Source my settings.
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/zsh/zshrc" ]]; then
  source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/zshrc"
fi

# Source boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh ]

# added by travis gem
[ -f /Users/jason/.travis/travis.sh ] && source /Users/jason/.travis/travis.sh
